/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * eiPrintManager.java
 *
 * Created on 25.04.2010, 17:28:34
 */

package GUI;
import Communication.MCCmdRSP;
import Communication.Parsedata;
import eiPrint.OBJMgmt.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.Popup;
import javax.swing.PopupFactory;


/**
 *
 * @author padrun
 */
public class eiPrintManager extends javax.swing.JFrame {

    private File file;
   // private DisplayPanel ballonPanel;
    private MCCmdRSP laser;

    /** Creates new form eiPrintManager */
    public eiPrintManager() {
        initComponents();


        laser = new MCCmdRSP();


//        ballonPanel = new DisplayPanel();
//        viewObject.add(ballonPanel);
//
//        viewObject.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Scan = new javax.swing.JButton();
        STOP = new javax.swing.JButton();
        Print = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        viewSujet = new javax.swing.JPanel();
        Sujet = new javax.swing.JLabel();
        Open = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Pfad = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        SerialPort = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Version = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Control"));

        Scan.setBackground(new java.awt.Color(0, 153, 51));
        Scan.setText("SCAN");
        Scan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScanActionPerformed(evt);
            }
        });

        STOP.setBackground(new java.awt.Color(255, 0, 0));
        STOP.setText("STOP");
        STOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STOPActionPerformed(evt);
            }
        });

        Print.setBackground(new java.awt.Color(0, 51, 204));
        Print.setText("PRINT");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        jLabel1.setText("Elapsed Time:");

        jTextField1.setText("00:00:00");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Scan)
                        .addGap(18, 18, 18)
                        .addComponent(Print)
                        .addGap(18, 18, 18)
                        .addComponent(STOP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Scan)
                    .addComponent(Print)
                    .addComponent(STOP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        viewSujet.setBorder(javax.swing.BorderFactory.createTitledBorder("View Sujet"));

        Sujet.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Sujet.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewSujetLayout = new javax.swing.GroupLayout(viewSujet);
        viewSujet.setLayout(viewSujetLayout);
        viewSujetLayout.setHorizontalGroup(
            viewSujetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSujetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewSujetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sujet, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addGroup(viewSujetLayout.createSequentialGroup()
                        .addComponent(Open)
                        .addGap(18, 18, 18)
                        .addComponent(Save)))
                .addContainerGap())
        );
        viewSujetLayout.setVerticalGroup(
            viewSujetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSujetLayout.createSequentialGroup()
                .addComponent(Sujet, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewSujetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Open)
                    .addComponent(Save))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Monitor"));

        jLabel2.setText("Event Handling");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Debug Log");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(180, 180, 180)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Store"));

        Pfad.setText("Pfad");
        Pfad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PfadActionPerformed(evt);
            }
        });

        jTextField4.setText("E:/Hta/PREN/Subversion/eiPrint/src/eiPrint/OBJM");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Pfad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pfad))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Open");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("config");

        SerialPort.setText("Serial Port");
        SerialPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerialPortActionPerformed(evt);
            }
        });
        jMenu3.add(SerialPort);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("about");

        Version.setText("Version");
        Version.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VersionActionPerformed(evt);
            }
        });
        jMenu4.add(Version);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewSujet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewSujet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        viewSujet.getAccessibleContext().setAccessibleName("View ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.openFile();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void ScanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScanActionPerformed

        // starts David Laser Scan
        
        //MCCmdRSP laser = new MCCmdRSP();
        try {
            laser.startLaser();
            this.enableStopButton(true);
            this.enablePrintButton(true);
        } catch (IOException ex) {
            //this.enableStopButton(true);
            //this.enablePrintButton(true);
            System.out.println(ex);
        }
    }//GEN-LAST:event_ScanActionPerformed

    private void STOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STOPActionPerformed
        // TODO add your handling code here:

        //MCCmdRSP laser = new MCCmdRSP();
        
        try {
            laser.stop();
            //laser.neutralPos();
        } catch (IOException ex) {
            System.out.println(ex);
            //Logger.getLogger(eiPrintManager.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_STOPActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveActionPerformed

    private void SerialPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerialPortActionPerformed

      JFrame frame;
      Popup popup;

      frame = new JFrame("Serial Config");
      frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      frame.setSize(500, 300);

      PopupFactory factory = PopupFactory.getSharedInstance();
      popup = factory.getPopup(frame, new JButton("JButton"), 50, 50);
      popup.show();

      frame.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_SerialPortActionPerformed

    private void VersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VersionActionPerformed
        // TODO add your handling code here:

      JFrame frame;
      Popup popup;

      frame = new JFrame("Version");
      frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      frame.setSize(500, 300);

      PopupFactory factory = PopupFactory.getSharedInstance();
      popup = factory.getPopup(frame, new JButton("JButton"), 50, 50);
      System.out.println("Version: 1.03");
      popup.show();

      frame.setVisible(true);


    }//GEN-LAST:event_VersionActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        String filefolder = "";
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Please select Folder with ObjectFiles");

        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION){
            file = fc.getSelectedFile();
            filefolder = file.getAbsolutePath();
        }

      //Objektfile_einlesen o = new Objektfile_einlesen("D:/HTA/PREN/Subversion/eiPrint/src/eiPrint/OBJMgmt/data/BallonMaxV1.txt","D:/HTA/PREN/Subversion/eiPrint/src/eiPrint/OBJMgmt/data/sujet.txt");
      Objektfile_einlesen o = new Objektfile_einlesen(filefolder+"\\BallonMaxV1.txt",filefolder+"\\sujet.txt");
        try {
//            try {
//                o.fileEinlesen();
//            } catch (ClassNotFoundException ex) {
//                Logger.getLogger(eiPrintManager.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            o.saveToDb();
            o.sujetEinlesen();
        } catch (IOException ex) {
            Logger.getLogger(eiPrintManager.class.getName()).log(Level.SEVERE, null, ex);
        }
      o.generiereDruckdaten(o.getOrigin().get(0).getX(), o.getOrigin().get(0).getY(), o.getOrigin().get(0).getZ());

      Parsedata PData = new Parsedata();
      
      PData.parsedata(o.getStepsArray());

      
        try {
          laser.neutralPos();
          //laser.writetoport(printArrayColorChange);
          laser.writetoport(PData.printArray);
        } catch (IOException ex) {
            System.out.println(ex);
        }
        //MCCmdRSP laser = new MCCmdRSP();
//       int i;
//
//       byte[][] printArrayColorChange = new byte [300][5];
//
//       for (i=0;i<250;i++){
//            printArrayColorChange[i][0] = 1;
//            printArrayColorChange[i][1] = 1;
//            printArrayColorChange[i][2] = 1;
//            printArrayColorChange[i][3] = 1;
//            printArrayColorChange[i][4] = 1;
//       }

//       for (i=200;i<300;i++){
//
//            printArrayColorChange[i][0] = 1;
//            printArrayColorChange[i][1] = 0;
//            printArrayColorChange[i][2] = 0;
//            printArrayColorChange[i][3] = 2;
//            printArrayColorChange[i][4] = 1;
//       }







//       byte[][] printArray = new byte[256][5];
// //-------------------------------------------//
//// Array for due motor spep forwards
////--------------------------------------------//
//
//        for(i=0; i<=199;i++){
//            printArray[i][0] = 1;
//            printArray[i][1] = 1;
//            printArray[i][2] = 1;
//            printArray[i][3] = 0;
//            printArray[i][4] = 0;
//
//       }
//
////-------------------------------------------//
//// Array for due motor spep backwards
////--------------------------------------------//
//
//       // for (i=100; i<150; i=i+3) {
//          for (i=200; i<=250; i++)  {
//            printArray[i][0] = -1;
//            printArray[i][1] = 0;
//            printArray[i][2] = 0;
//            printArray[i][3] = 0;
//            printArray[i][4] = 0;
//
//            i++;
//
//            printArray[i][0] = 0;
//            printArray[i][1] = -1;
//            printArray[i][2] = 0;
//            printArray[i][3] = 0;
//            printArray[i][4] = 0;
//
//            i++;
//
//            printArray[i][0] = 0;
//            printArray[i][1] = 0;
//            printArray[i][2] = -1;
//            printArray[i][3] = 0;
//            printArray[i][4] = 0;
//
//       }
//
// //-------------------------------------------//
//// change Color
////--------------------------------------------//
////            for (i=150; i<160; i=i+5) {
//            for (i=250; i<=253; i++) {
//            printArray[i][0] = 0;
//            printArray[i][1] = 0;
//            printArray[i][2] = 0;
//            printArray[i][3] = 1;
//            printArray[i][4] = 0;
//
//            i++;
//
//            printArray[i][0] = 0;
//            printArray[i][1] = 0;
//            printArray[i][2] = 0;
//            printArray[i][3] = 2;
//            printArray[i][4] = 0;
//
//            i++;
//
//            printArray[i][0] = 0;
//            printArray[i][1] = 0;
//            printArray[i][2] = 0;
//            printArray[i][3] = 0;
//            printArray[i][4] = 0;
//
//            }
////-------------------------------------------//
////       write
////--------------------------------------------//
//
//            for (i=253; i<=254; i++) {
//
//            printArray[i][0] = 0;
//            printArray[i][1] = 0;
//            printArray[i][2] = 0;
//            printArray[i][3] = 0;
//            printArray[i][4] = 0;
//
//            i++;
//
//            printArray[i][0] = 0;
//            printArray[i][1] = 0;
//            printArray[i][2] = 0;
//            printArray[i][3] = 0;
//            printArray[i][4] = 1;
//       }
//
//        try {
//          laser.neutralPos();
//          //laser.writetoport(printArrayColorChange);
//          laser.writetoport(printArrayColorChange);
//        } catch (IOException ex) {
//            System.out.println(ex);
//        }

    }//GEN-LAST:event_PrintActionPerformed

    private void PfadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PfadActionPerformed
        // TODO add your handling here:

//        String path = "D:\\HTA\\PREN\\Subversion\\eiPrint\\src\\eiPrint";
        String path = "C:\\Users\\Optimus Prime\\Documents\\NetBeansProjects\\src\\eiPrint";

        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Please select Log Path");

        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION){
            path = fc.getSelectedFile().getAbsolutePath();
        }

        this.jTextField4.setText(path);


    }//GEN-LAST:event_PfadActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        // TODO add your handling code here:
        this.openFile();
    }//GEN-LAST:event_OpenActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eiPrintManager().setVisible(true);
            }
        });
    }


    public void openFile(){
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle("Please select Image File");

        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = fc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION){
            file = fc.getSelectedFile();
            ImageIcon icon = new ImageIcon(file.getAbsolutePath());
            Sujet.setIcon(icon);
        }
    }

    public void enableStopButton(boolean state){
        if(state){
            this.STOP.setEnabled(true);
        }else{
            this.STOP.setEnabled(false);
        }
    }

    public void enablePrintButton(boolean state){
        if(state){
            this.Print.setEnabled(true);
        }else{
            this.Print.setEnabled(false);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Open;
    private javax.swing.JButton Pfad;
    private javax.swing.JButton Print;
    private javax.swing.JButton STOP;
    private javax.swing.JButton Save;
    private javax.swing.JButton Scan;
    private javax.swing.JMenuItem SerialPort;
    private javax.swing.JLabel Sujet;
    private javax.swing.JMenuItem Version;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel viewSujet;
    // End of variables declaration//GEN-END:variables

}
